SELECT USUARIO.IDUSUARIO,( PERSONA.NOMBRE+' '+ PERSONA.APELLIDO)NOMBRE_COMPLETO, ROL.NOMBRE AS NOMBRE_ROL, USUARIOROL.FECHAASIGNA
FROM  USUARIO INNER JOIN
                         PERSONA ON USUARIO.IDPERSONA = PERSONA.IDPERSONA INNER JOIN
                         USUARIOROL ON USUARIO.IDUSUARIO = USUARIOROL.IDUSUARIO INNER JOIN
                         ROL ON USUARIOROL.IDROL = ROL.IDROL
--UsuarioROL
SELECT        USUARIOROL.IDUSUARIOROL, USUARIO.NOMBREUSER, USUARIO.CONTRASEÑA, ROL.NOMBRE, USUARIOROL.FECHAASIGNA, USUARIOROL.ESTADO
FROM            USUARIOROL INNER JOIN
                         USUARIO ON USUARIOROL.IDUSUARIO = USUARIO.IDUSUARIO INNER JOIN
                         ROL ON USUARIOROL.IDROL = ROL.IDROL
--Cliente
SELECT        CLIENTE.IDCLIENTE, CLIENTE.TIPOCLIENTE, CLIENTE.CODIGOCLIENTE, PERSONA.NOMBRE, PERSONA.APELLIDO
FROM            CLIENTE INNER JOIN
                         PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA
--Venta
SELECT        VENTA.IDVENTA, CLIENTE.CODIGOCLIENTE, USUARIO.NOMBREUSER, VENTA.FECHA, VENTA.TOTAL, VENTA.ESTADO
FROM            VENTA INNER JOIN
                         CLIENTE ON VENTA.IDCLIENTE = CLIENTE.IDCLIENTE INNER JOIN
                         USUARIO ON VENTA.IDVENDEDOR = USUARIO.IDUSUARIO INNER JOIN
                         USUARIOROL ON USUARIO.IDUSUARIO = USUARIOROL.IDUSUARIO

--DedtalleVenta
SELECT        DETALLEVENTA.IDDETALLEVENTA, VENTA.FECHA, PRODUCTO.NOMBRE, PRODUCTO.CODIGOBARRA, DETALLEVENTA.CANTIDAD, DETALLEVENTA.PRECIOVENTA, DETALLEVENTA.ESTADO
FROM            DETALLEVENTA INNER JOIN
                         VENTA ON DETALLEVENTA.IDVENTA = VENTA.IDVENTA INNER JOIN
                         PRODUCTO ON DETALLEVENTA.IDPRODUCTO = PRODUCTO.IDPRODUCTO
--DetalleIng
SELECT        DETALLEING.IDDETALLEING, PRODUCTO.NOMBRE, PRODUCTO.CODIGOBARRA, PRODUCTO.UNIDAD, INGRESO.FECHAINGRESO, DETALLEING.FECHAVENC, DETALLEING.CANTIDAD, DETALLEING.PRECIOCOSTO, 
                         DETALLEING.PRECIOVENTA, DETALLEING.SUBTOTAL
FROM            DETALLEING INNER JOIN
                         PRODUCTO ON DETALLEING.IDPRODUCTO = PRODUCTO.IDPRODUCTO INNER JOIN
                         INGRESO ON DETALLEING.IDINGRESO = INGRESO.IDINGRESO
--Ingreso
SELECT        INGRESO.IDINGRESO, PROVEEDOR.NOMBRE, PROVEEDOR.DIRECCION, INGRESO.FECHAINGRESO, INGRESO.TOTAL, INGRESO.ESTADO
FROM            INGRESO INNER JOIN
                         PROVEEDOR ON INGRESO.IDPROVEEDOR = PROVEEDOR.IDPROVEEDOR
--Producto
SELECT    PRODUCTO.IDPRODUCTO, TIPOPROD.NOMBRE, MARCA.NOMBRE AS MARCA, PRODUCTO.NOMBRE AS NOMBREPRODUCTO, PRODUCTO.CODIGOBARRA, PRODUCTO.UNIDAD, PRODUCTO.DESCRIPCION
FROM      PRODUCTO INNER JOIN
                         TIPOPROD ON PRODUCTO.IDTIPOPROD = TIPOPROD.IDTIPOPROD INNER JOIN
                         MARCA ON PRODUCTO.IDMARCA = MARCA.IDMARCA
--Provee
SELECT        PROVEE.IDPROVEE, PRODUCTO.NOMBRE, PRODUCTO.UNIDAD, PRODUCTO.DESCRIPCION, PROVEEDOR.NOMBRE AS Expr1, PROVEEDOR.DIRECCION, PROVEE.FECHA, PROVEE.PRECIO
FROM            PROVEE INNER JOIN
                         PRODUCTO ON PROVEE.IDPRODUCTO = PRODUCTO.IDPRODUCTO INNER JOIN
                         PROVEEDOR ON PROVEE.IDPROVEEDOR = PROVEEDOR.IDPROVEEDOR

